// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.PsWinkelen.Domain.Models
{
    using Newtonsoft.Json;

    public partial class Bestelregel
    {
        /// <summary>
        /// Initializes a new instance of the Bestelregel class.
        /// </summary>
        public Bestelregel() { }

        /// <summary>
        /// Initializes a new instance of the Bestelregel class.
        /// </summary>
        public Bestelregel(int? artikelId = default(int?), int? aantalArtikelen = default(int?), string artikelBeschrijving = default(string), string artikelNaam = default(string), double? prijsPerArtikelInc = default(double?), double? prijsPerArtikelExc = default(double?), string afbeeldingUrl = default(string), string leverancierCode = default(string))
        {
            ArtikelId = artikelId;
            AantalArtikelen = aantalArtikelen;
            ArtikelBeschrijving = artikelBeschrijving;
            ArtikelNaam = artikelNaam;
            PrijsPerArtikelInc = prijsPerArtikelInc;
            PrijsPerArtikelExc = prijsPerArtikelExc;
            AfbeeldingUrl = afbeeldingUrl;
            LeverancierCode = leverancierCode;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelId")]
        public int? ArtikelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aantalArtikelen")]
        public int? AantalArtikelen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelBeschrijving")]
        public string ArtikelBeschrijving { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelNaam")]
        public string ArtikelNaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prijsPerArtikelInc")]
        public double? PrijsPerArtikelInc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prijsPerArtikelExc")]
        public double? PrijsPerArtikelExc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "afbeeldingUrl")]
        public string AfbeeldingUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leverancierCode")]
        public string LeverancierCode { get; set; }

    }
}
