// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.PsWinkelen.Domain.Models
{
    using Newtonsoft.Json;

    public partial class Klantgegevens
    {
        /// <summary>
        /// Initializes a new instance of the Klantgegevens class.
        /// </summary>
        public Klantgegevens() { }

        /// <summary>
        /// Initializes a new instance of the Klantgegevens class.
        /// </summary>
        public Klantgegevens(int? klantId = default(int?), string naam = default(string), string land = default(string), string straatnaam = default(string), string huisnummer = default(string), string postcode = default(string), string woonplaats = default(string))
        {
            KlantId = klantId;
            Naam = naam;
            Land = land;
            Straatnaam = straatnaam;
            Huisnummer = huisnummer;
            Postcode = postcode;
            Woonplaats = woonplaats;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantId")]
        public int? KlantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "naam")]
        public string Naam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "land")]
        public string Land { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "straatnaam")]
        public string Straatnaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "huisnummer")]
        public string Huisnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postcode")]
        public string Postcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "woonplaats")]
        public string Woonplaats { get; set; }

    }
}
