// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lapiwe.GMS.FrontEnd.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MeldOnderhoudsOpdrachtAanCommand
    {
        /// <summary>
        /// Initializes a new instance of the MeldOnderhoudsOpdrachtAanCommand
        /// class.
        /// </summary>
        public MeldOnderhoudsOpdrachtAanCommand() { }

        /// <summary>
        /// Initializes a new instance of the MeldOnderhoudsOpdrachtAanCommand
        /// class.
        /// </summary>
        public MeldOnderhoudsOpdrachtAanCommand(Guid klantGuid, Guid autoGuid, DateTime aanmeldDatum, int kilometerstand, string opdrachtOmschrijving, bool apk, DateTime? timeStamp = default(DateTime?), Guid? correlationID = default(Guid?))
        {
            KlantGuid = klantGuid;
            AutoGuid = autoGuid;
            AanmeldDatum = aanmeldDatum;
            Kilometerstand = kilometerstand;
            OpdrachtOmschrijving = opdrachtOmschrijving;
            Apk = apk;
            TimeStamp = timeStamp;
            CorrelationID = correlationID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantGuid")]
        public Guid KlantGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "autoGuid")]
        public Guid AutoGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aanmeldDatum")]
        public DateTime AanmeldDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kilometerstand")]
        public int Kilometerstand { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "opdrachtOmschrijving")]
        public string OpdrachtOmschrijving { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apk")]
        public bool Apk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public DateTime? TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationID")]
        public Guid? CorrelationID { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (OpdrachtOmschrijving == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "OpdrachtOmschrijving");
            }
        }
    }
}
