// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lapiwe.GMS.FrontEnd.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class StartOnderhoudOpdrachtCommand
    {
        /// <summary>
        /// Initializes a new instance of the StartOnderhoudOpdrachtCommand
        /// class.
        /// </summary>
        public StartOnderhoudOpdrachtCommand() { }

        /// <summary>
        /// Initializes a new instance of the StartOnderhoudOpdrachtCommand
        /// class.
        /// </summary>
        public StartOnderhoudOpdrachtCommand(Guid onderhoudOpdrachtGuid, DateTime? timeStamp = default(DateTime?), Guid? correlationID = default(Guid?))
        {
            OnderhoudOpdrachtGuid = onderhoudOpdrachtGuid;
            TimeStamp = timeStamp;
            CorrelationID = correlationID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onderhoudOpdrachtGuid")]
        public Guid OnderhoudOpdrachtGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStamp")]
        public DateTime? TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationID")]
        public Guid? CorrelationID { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
