// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.PsWinkelen.Infrastructure.Agents
{
    using Domain.Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for BestellingenBeheerService.
    /// </summary>
    public static partial class BestellingenBeheerServiceExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='bestellingToevoegenCommand'>
            /// </param>
            public static object PostBestellingToevoegen(this IBestellingenBeheerService operations, BestellingToevoegenCommand bestellingToevoegenCommand = default(BestellingToevoegenCommand))
            {
                return Task.Factory.StartNew(s => ((IBestellingenBeheerService)s).PostBestellingToevoegenAsync(bestellingToevoegenCommand), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='bestellingToevoegenCommand'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostBestellingToevoegenAsync(this IBestellingenBeheerService operations, BestellingToevoegenCommand bestellingToevoegenCommand = default(BestellingToevoegenCommand), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostBestellingToevoegenWithHttpMessagesAsync(bestellingToevoegenCommand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
