// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.FeWEbshop.Infrastructure.Agents.PsWinkelen.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Artikel
    {
        /// <summary>
        /// Initializes a new instance of the Artikel class.
        /// </summary>
        public Artikel() { }

        /// <summary>
        /// Initializes a new instance of the Artikel class.
        /// </summary>
        public Artikel(int? artikelnummer = default(int?), string naam = default(string), string beschrijving = default(string), double? prijs = default(double?), double? prijsInclBtw = default(double?), string afbeeldingUrl = default(string), DateTime? leverbaarVanaf = default(DateTime?), DateTime? leverbaarTot = default(DateTime?), string leverancierCode = default(string), string leverancier = default(string), bool? inCatalog = default(bool?))
        {
            Artikelnummer = artikelnummer;
            Naam = naam;
            Beschrijving = beschrijving;
            Prijs = prijs;
            PrijsInclBtw = prijsInclBtw;
            AfbeeldingUrl = afbeeldingUrl;
            LeverbaarVanaf = leverbaarVanaf;
            LeverbaarTot = leverbaarTot;
            LeverancierCode = leverancierCode;
            Leverancier = leverancier;
            InCatalog = inCatalog;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "artikelnummer")]
        public int? Artikelnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "naam")]
        public string Naam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "beschrijving")]
        public string Beschrijving { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prijs")]
        public double? Prijs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prijsInclBtw")]
        public double? PrijsInclBtw { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "afbeeldingUrl")]
        public string AfbeeldingUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leverbaarVanaf")]
        public DateTime? LeverbaarVanaf { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leverbaarTot")]
        public DateTime? LeverbaarTot { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leverancierCode")]
        public string LeverancierCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leverancier")]
        public string Leverancier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inCatalog")]
        public bool? InCatalog { get; set; }

    }
}
