// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.FeWEbshop.Infrastructure.Agents.PsWinkelen.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BestellingResult
    {
        /// <summary>
        /// Initializes a new instance of the BestellingResult class.
        /// </summary>
        public BestellingResult() { }

        /// <summary>
        /// Initializes a new instance of the BestellingResult class.
        /// </summary>
        public BestellingResult(FullBestelling bestelling = default(FullBestelling), bool? isValid = default(bool?), IList<string> errors = default(IList<string>))
        {
            Bestelling = bestelling;
            IsValid = isValid;
            Errors = errors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bestelling")]
        public FullBestelling Bestelling { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isValid")]
        public bool? IsValid { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<string> Errors { get; set; }

    }
}
