// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.FeWEbshop.Infrastructure.Agents.PsWinkelen.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Klant
    {
        /// <summary>
        /// Initializes a new instance of the Klant class.
        /// </summary>
        public Klant() { }

        /// <summary>
        /// Initializes a new instance of the Klant class.
        /// </summary>
        public Klant(int? klantId = default(int?), string naam = default(string), string land = default(string), string postcode = default(string), string huisnummer = default(string), string straatnaam = default(string), string plaats = default(string))
        {
            KlantId = klantId;
            Naam = naam;
            Land = land;
            Postcode = postcode;
            Huisnummer = huisnummer;
            Straatnaam = straatnaam;
            Plaats = plaats;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "klantId")]
        public int? KlantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "naam")]
        public string Naam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "land")]
        public string Land { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postcode")]
        public string Postcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "huisnummer")]
        public string Huisnummer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "straatnaam")]
        public string Straatnaam { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "plaats")]
        public string Plaats { get; set; }

    }
}
