// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Case1.AdministratieCursusenCursisten.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AddFromFileResultReport
    {
        /// <summary>
        /// Initializes a new instance of the AddFromFileResultReport class.
        /// </summary>
        public AddFromFileResultReport() { }

        /// <summary>
        /// Initializes a new instance of the AddFromFileResultReport class.
        /// </summary>
        public AddFromFileResultReport(string errorMessage = default(string), int? aantalAddedItems = default(int?), int? aantalDuplicateItems = default(int?))
        {
            ErrorMessage = errorMessage;
            AantalAddedItems = aantalAddedItems;
            AantalDuplicateItems = aantalDuplicateItems;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aantalAddedItems")]
        public int? AantalAddedItems { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aantalDuplicateItems")]
        public int? AantalDuplicateItems { get; private set; }

    }
}
