// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Case1.AdministratieCursusenCursisten.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Cursus
    {
        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus() { }

        /// <summary>
        /// Initializes a new instance of the Cursus class.
        /// </summary>
        public Cursus(string code = default(string), int? duur = default(int?), string titel = default(string))
        {
            Code = code;
            Duur = duur;
            Titel = titel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duur")]
        public int? Duur { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "titel")]
        public string Titel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Code != null)
            {
                if (this.Code.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Code", 10);
                }
                if (this.Code.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Code", 0);
                }
            }
            if (this.Titel != null)
            {
                if (this.Titel.Length > 300)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Titel", 300);
                }
                if (this.Titel.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Titel", 0);
                }
            }
        }
    }
}
