// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Minor.Case1.AdministratieCursusenCursisten.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CursusInstantie
    {
        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie() { }

        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie(int? id = default(int?), DateTime? startDatum = default(DateTime?), string cursusCode = default(string), Cursus cursus = default(Cursus))
        {
            Id = id;
            StartDatum = startDatum;
            CursusCode = cursusCode;
            Cursus = cursus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDatum")]
        public DateTime? StartDatum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursusCode")]
        public string CursusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursus")]
        public Cursus Cursus { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CursusCode != null)
            {
                if (this.CursusCode.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CursusCode", 10);
                }
                if (this.CursusCode.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CursusCode", 0);
                }
            }
            if (this.Cursus != null)
            {
                this.Cursus.Validate();
            }
        }
    }
}
