//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rdw.nl", IsNullable=false)]
public partial class keuringsverzoek {
    
    private keuringsverzoekVoertuig voertuigField;
    
    private System.DateTime keuringsdatumField;
    
    private keuringsinstantie keuringsinstantieField;
    
    private string correlatieIdField;
    
    /// <remarks/>
    public keuringsverzoekVoertuig voertuig {
        get {
            return this.voertuigField;
        }
        set {
            this.voertuigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk", DataType="date")]
    public System.DateTime keuringsdatum {
        get {
            return this.keuringsdatumField;
        }
        set {
            this.keuringsdatumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk")]
    public keuringsinstantie keuringsinstantie {
        get {
            return this.keuringsinstantieField;
        }
        set {
            this.keuringsinstantieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string correlatieId {
        get {
            return this.correlatieIdField;
        }
        set {
            this.correlatieIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl")]
public partial class keuringsverzoekVoertuig {
    
    private string kentekenField;
    
    private int kilometerstandField;
    
    private string naamField;
    
    private voertuigtype typeField;
    
    public keuringsverzoekVoertuig() {
        this.typeField = voertuigtype.personenauto;
    }
    
    /// <remarks/>
    public string kenteken {
        get {
            return this.kentekenField;
        }
        set {
            this.kentekenField = value;
        }
    }
    
    /// <remarks/>
    public int kilometerstand {
        get {
            return this.kilometerstandField;
        }
        set {
            this.kilometerstandField = value;
        }
    }
    
    /// <remarks/>
    public string naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(voertuigtype.personenauto)]
    public voertuigtype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rdw.nl")]
public enum voertuigtype {
    
    /// <remarks/>
    personenauto,
    
    /// <remarks/>
    motor,
    
    /// <remarks/>
    vrachttransport,
    
    /// <remarks/>
    personentransport,
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rdw.nl")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rdw.nl", IsNullable=false)]
public partial class keuringsregistratie {
    
    private string kentekenField;
    
    private System.DateTime keuringsdatumField;
    
    private System.Nullable<System.DateTime> steekproefField;
    
    private bool steekproefFieldSpecified;
    
    private string correlatieIdField;
    
    /// <remarks/>
    public string kenteken {
        get {
            return this.kentekenField;
        }
        set {
            this.kentekenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk", DataType="date")]
    public System.DateTime keuringsdatum {
        get {
            return this.keuringsdatumField;
        }
        set {
            this.keuringsdatumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rdw.nl/apk", DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> steekproef {
        get {
            return this.steekproefField;
        }
        set {
            this.steekproefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool steekproefSpecified {
        get {
            return this.steekproefFieldSpecified;
        }
        set {
            this.steekproefFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string correlatieId {
        get {
            return this.correlatieIdField;
        }
        set {
            this.correlatieIdField = value;
        }
    }
}
