version: '2'

services:
  haz.fewebshop.listener:
    image: heroesandzeroes/haz.fewebshop.listener${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: obj/Docker/empty/
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
