// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HAZ.FeWEbshop.Infrastructure.Agents.PsWinkelen
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for PsWinkelenClient.
    /// </summary>
    public static partial class PsWinkelenClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void TestJson(this IPsWinkelenClient operations)
            {
                Task.Factory.StartNew(s => ((IPsWinkelenClient)s).TestJsonAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task TestJsonAsync(this IPsWinkelenClient operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.TestJsonWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startBestellingCommand'>
            /// </param>
            public static object StartBestelling(this IPsWinkelenClient operations, FullBestelling startBestellingCommand = default(FullBestelling))
            {
                return Task.Factory.StartNew(s => ((IPsWinkelenClient)s).StartBestellingAsync(startBestellingCommand), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startBestellingCommand'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> StartBestellingAsync(this IPsWinkelenClient operations, FullBestelling startBestellingCommand = default(FullBestelling), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.StartBestellingWithHttpMessagesAsync(startBestellingCommand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
