version: '2'

services:
  haz.pswinkelen.api:
    image: user/haz.pswinkelen.api${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: obj/Docker/empty/
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
  haz.pswinkelen.mysql:
    volumes:
    - /c/docker/pswinkelen/mysql:/var/lib/mysql
