version: '2'

services:
  lapiwe.gms.frontend:
    image: lars/lapiwe.gms.frontend${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6030:80
    networks:
      - eventbus-network
    links:
      - frontend-db:db

  frontend-db:
    image: mysql
    container_name: mysql-frontend
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: frontendDB
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 12341234
    ports:
      - 6032:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-frontend
    ports:
     - 6031:80
    links:
     - frontend-db:db

networks:
  eventbus-network:
    external:
      name: eventbus-network